name: Sincronizador de Dados Financeiros (D-0)

on:
  schedule:
    # 1. Roda de segunda a sexta (1-5) das 12h às 21h UTC (09h às 18h BRT) para cotações horárias
    - cron: '0 12-21 * * 1-5'
    
    # 2. Roda no dia 1º de todo mês às 07:00 UTC (que equivale exatamente às 04:00 BRT) para o histórico mensal
    - cron: '0 7 1 * *'

  workflow_dispatch:

jobs:
  maestro-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        uses: pip install pandas requests pymongo yfinance # (Ajustado para o formato padrão do run)

      - name: Rodar Script Maestro
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python scripts/sync_cache.py
